### PR TITLE
count set bits in positive integer

### PR DESCRIPTION
**Pull request by neodark**
Hell @pravee42 : Here is a PR  with some python code to count set bits in positive integer.

I have read the contributing guidelines but haven't found any issues to be fixed related to this.

If I should do something before please let me know, I will be happy to change anything if required.

Could you please add the hacktoberfest label to this PR :slightly_smiling_face: Thanks in advance.

### CODE REVIEW

**Comment by pravee42** [comment]
Can you please create an issue and type in the issue number here

**Comment by neodark** [comment]
This PR solves the issue #60

**Comment by neodark** [comment]
> Can you please create an issue and type in the issue number here

Sure. It's done. Thanks a lot! :+1:

**Comment by pravee42** [comment]
PR accepted bro

Regards,
*Praveen Kumar D,*
*Founder and CEO of Abipravi <https://g.page/abipravi?share>.*
Github : https://github.com/pravee42
Medium : https://abipravi.medium.com/
Blog : https://abipraviii.blogspot.com/

**Comment by pravee42** [comment]
✅✅
Regards,
*Praveen Kumar D,*
*Founder and CEO of Abipravi <https://g.page/abipravi?share>.*
Github : https://github.com/pravee42
Medium : https://abipravi.medium.com/
Blog : https://abipraviii.blogspot.com/

**Pull request merged**
