### PR TITLE
Python program to check a password's strength

### PR DESCRIPTION
**Pull request by Ansfred**
Simple python code, that takes a random string as input. Here in our case, the string is expected to be a password. Performs the necessary checks, and deems the password as strong or weak.

### CODE REVIEW

**Comment by pravee42** [comment]
You need to create an issue and then enter the issue number here

**Comment by Ansfred** [comment]
Issue #62

**Comment by Ansfred** [comment]
@pravee42 , I have made an issue, an attached the issue number, kindly verify 😊

**Comment by pravee42** [comment]
closes #62

**Pull request merged**
