### PR TITLE
Quadratic Equation Solver in Python

### PR DESCRIPTION
**Pull request by DeepraMazumder**
This is the first time I am participating in a Hacktoberfest.

### CODE REVIEW

**Comment by pravee42** [comment]
Can you please explain you code

**Review by pravee42 — COMMENTED** [review]
This isn't seems correct

**Comment by DeepraMazumder** [comment]
> Can you please explain you code

Sorry, there was a technical glitch from my end.

**Comment by DeepraMazumder** [comment]
> This isn't seems correct

I have edited my code.

**Pull request merged**
