### PR TITLE
Added program to swap columns in zig-zag manner

### PR DESCRIPTION
**Pull request by LiteBrick204**
This program accepts a rxc matrix and swaps the column in zig-zag manner.

### CODE REVIEW

**Comment by pravee42** [comment]
Can send the screenshots of working demo

**Review by pravee42 — COMMENTED** [review]
It is basically an transpose of an matrix

**Comment by LiteBrick204** [comment]
Thank you :)

**Comment by pravee42** [comment]
> Thank you :)

Git a star to this repo

**Pull request merged**
